Fix 1700 override warnings [-Winconsistent-missing-override]
Classes should either use or not use override, otherwise it hurts
code readability.

Some inline keywords were removed because of an error with MSVC2010:
error C2216: 'override' cannot be used with 'inline'

Change-Id: I7276d5525a92281bd0d743beb11d0dc73441443b
Reviewed-by: Marc Mutz <marc.mutz@kdab.com>

cregit: ad2ea165501c23cbd85c4ddb155f2d7ea8fc85b8 https://github.com/qt/qtbase/commit/ad2ea165501c23cbd85c4ddb155f2d7ea8fc85b8