Fix QtWidget function-unused warnings found by Clang 3.4
qwidgetbackingstore.cpp:72:20: error: unused function 'qRectIntersects' [-Werror,-Wunused-function]

Change-Id: Ia3afe8f0547fa86804093281db89efabe68b34a1
Reviewed-by: Robin Burchell <robin+qt@viroteck.net>

cregit: 47a0d64dcf1f3351e39d1dae8fc3a317ffc03c5e https://github.com/qt/qtbase/commit/47a0d64dcf1f3351e39d1dae8fc3a317ffc03c5e