clang: Fix compilation with -openssl-linked
Fixes errors like

qsslsocket_openssl_symbols.cpp:111:6: error:
      unused function 'qsslSocketUnresolvedSymbolWarning'
      [-Werror,-Wunused-function]
void qsslSocketUnresolvedSymbolWarning(const char *functionName)
     ^
1 error generated.

Change-Id: I164518de583f080724ab9a7165c885602a1c6231
Reviewed-by: Richard J. Moore <rich@kde.org>

cregit: 6c58c9b3ec78ecdd3f72f601041ac34bf2c59320 https://github.com/qt/qtbase/commit/6c58c9b3ec78ecdd3f72f601041ac34bf2c59320