Fix function-not-used warnings detected by Clang 3.4
These functions have been turned to static (although inline), which
means they need to be used or marked as possibly unused.

qglobal.h:712:37: error: unused function 'qFuzzyCompare' [-Werror,-Wunused-function]

Change-Id: Ie2ee713d26c86e0574b579c1ea42b9404c3d2035
Reviewed-by: Oswald Buddenhagen <oswald.buddenhagen@digia.com>

cregit: f4d3196e4f5d2f89f2d6564157402a78d454cca2 https://github.com/qt/qtbase/commit/f4d3196e4f5d2f89f2d6564157402a78d454cca2