Fix direct compilation of qtypeinfo.h and others
qtypeinfo.h is included by qglobal.h, so it needs to include that before
the #ifdef. Otherwise, we get a circular dependency problem with
qflags.h:

./QtCore/../../src/corelib/global/qflags.h:60:27: error: "Q_PRIMITIVE_TYPE" has not been declared

Also, take the opportunity to fix the other headers that are included
from qglobal.h to avoid similar problems in the future.

Change-Id: I99a56f42775c24bdcc796995b06509c1ca0cb849
Reviewed-by: Olivier Goffart <ogoffart@woboq.com>

cregit: 797f3c0a01e9adf0af3bc7c0bd3f7f63849d99b9 https://github.com/qt/qtbase/commit/797f3c0a01e9adf0af3bc7c0bd3f7f63849d99b9