Compile QLatin1String with C++11
qstring.h: In constructor ‘QLatin1String::QLatin1String(const QByteArray&)’:
qstring.h:667:129: error: ‘const char* QByteArray::constData() const’ is not ‘constexpr’

QByteArray has a destructor and therefore cannot be used in constexpr,
so do not mark it as constexpr

Change-Id: I037e9ae73a244660923eac791cc3e0082d1d7a63
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>

cregit: 09348c3efbfbb5713a8648988f42c2b6dc309508 https://github.com/qt/qtbase/commit/09348c3efbfbb5713a8648988f42c2b6dc309508