Remove unused private members
These members are in private classe, so we can safely remove them.

qpathclipper.cpp:762:9: error: private field 'm_point' is not used [-Werror,-Wunused-private-field]
qsimpledrag_p.h:100:20: error: private field 'm_cursor_drop_action' is not used
etc.

Change-Id: I35ed486eb959c49bb971700500a66411308ee7bc
Reviewed-by: Konstantin Ritt <ritt.ks@gmail.com>
Reviewed-by: Samuel Rødal <samuel.rodal@digia.com>
Reviewed-by: Gunnar Sletta <gunnar.sletta@digia.com>

cregit: c550a5d42c1188c0ccd11c205665e2608dbec61f https://github.com/qt/qtbase/commit/c550a5d42c1188c0ccd11c205665e2608dbec61f