Fix warnings reported by ICC in qdoc
doc.cpp(3292): error #68: integer conversion resulted in a change of sign
generator.cpp(363): error #68: integer conversion resulted in a change of sign

Change-Id: Ie714ffcb4098debc701ce3fb6fa444154ac02ae5
Reviewed-by: Jędrzej Nowacki <jedrzej.nowacki@digia.com>

cregit: a496b5dc38c96465e6ea4750ef293d8f2c3b6fc5 https://github.com/qt/qtbase/commit/a496b5dc38c96465e6ea4750ef293d8f2c3b6fc5