Fix compilation: testBit is only used if mtdev isn't
qevdevtouch.cpp:160:20: error: unused function 'testBit'

Change-Id: Idd9eee9b916c694bdfb963c00eeb0eaaf5618d40
Reviewed-by: Laszlo Agocs <laszlo.agocs@digia.com>

cregit: 71eb4d493956161b7e4aa48bb7c1d4c6309e5a10 https://github.com/qt/qtbase/commit/71eb4d493956161b7e4aa48bb7c1d4c6309e5a10