test: tst_qhttpsocketengine requires \`private_tests' set
Otherwise you get:

  undefined reference to \`vtable for QAbstractSocketEngine'

when -developer-build is not used.

Change-Id: I444140736a6bf736894dc12a20f6a4d48af2678e
Reviewed-by: Peter Hartmann <phartmann@blackberry.com>

cregit: fa907401e90364797b3e60223618b94b4b8776e5 https://github.com/qt/qtbase/commit/fa907401e90364797b3e60223618b94b4b8776e5