Fix warning about unused variable in qdoc
codeparser.cpp:245:18: error: unused variable ‘dn’ [-Werror=unused-variable]

Change-Id: Id271b3829ba3278e80d4e79746db7aabfabd751a
Reviewed-by: Olivier Goffart <ogoffart@woboq.com>

cregit: 96b48ee0cbd7261c11215226f8dcdfb07fa6ab77 https://github.com/qt/qtbase/commit/96b48ee0cbd7261c11215226f8dcdfb07fa6ab77