Fix change-of-sign warnings with ICC
qlocale_p.h(427): error #68: integer conversion resulted in a change of sign

We hadn't enabled Q_COMPILER_CONSTEXPR for ICC.

Change-Id: Ie7e3070b9f8f2cf512d2745001312865e698596b
Reviewed-by: Olivier Goffart <ogoffart@woboq.com>
Reviewed-by: Marc Mutz <marc.mutz@kdab.com>

cregit: f3e9f11265bc6715d4d1c6e2d734fad923b10d05 https://github.com/qt/qtbase/commit/f3e9f11265bc6715d4d1c6e2d734fad923b10d05