Fix compilation when including files created in shadow dirs
For normal #includes, moc simply ignores the missing file, but it could
generate problems later. It's a problem when the file being sought is
the FILE from plugin metadata. A very good example of this is Qt
Creator:

coreplugin.h:49: Error: Plugin Metadata file "Core.json" does not exist.

Change-Id: I16af04b477f52c6bd53c14147ec777b358dfdf50
Reviewed-by: Oswald Buddenhagen <oswald.buddenhagen@digia.com>

cregit: 49df5fc3d22669e8c534fc9985e9f4e09f8b2f62 https://github.com/qt/qtbase/commit/49df5fc3d22669e8c534fc9985e9f4e09f8b2f62