Fixed compile error in eglfs plugin due to narrowing conversion.
qeglfscursor.cpp:300: error: narrowing conversion of
‘((const QRectF*)r)->QRectF::left()’ from ‘qreal’ to ‘const GLfloat’
inside { }

Change-Id: Ic4273828ad361ffac5a68068372bf400d468fb38
Reviewed-by: Bradley T. Hughes <bradley.hughes@nokia.com>

cregit: 66a0b8446dbd4d77e117353c9a55630249eccf7e https://github.com/qt/qtbase/commit/66a0b8446dbd4d77e117353c9a55630249eccf7e