QWindows(XP)Style: fix build with Clang after includemocs run
Clang doesn't like the unused member variable:

  qwindowsstyle_p.h:100:11: error: private field 'reserved' is not used [-Werror,-Wunused-private-field]

Remove. It's private API.

Triggered by Clang seeing all methods of the classes in
one TU by the following includemocs commit.

Change-Id: I84e92d63af573c090ef89c1d8ee19af30f90b171
Reviewed-by: Friedemann Kleint <Friedemann.Kleint@theqtcompany.com>
Reviewed-by: Olivier Goffart (Woboq GmbH) <ogoffart@woboq.com>

cregit: 5655f3413151beb0abaeb847942f7bf29a114d7d https://github.com/qt/qtbase/commit/5655f3413151beb0abaeb847942f7bf29a114d7d