Work around ICC compatibility problem with Apple headers
Apple uses __OSX_AVAILABLE_STARTING in enum values too, which ICC
doesn't like. We need to force at least OS X 10.9 so we don't run into
build errors.

FSEvents.h(279): error: expected a "}"
    kFSEventStreamCreateFlagMarkSelf __OSX_AVAILABLE_STARTING(__MAC_10_9, __IPHONE_7_0) = 0x00000020
                                     ^

Intel issue ID: 6000071924
Change-Id: Iae1abb8e8e92f228571c5064d96e9d33d3e35173
Reviewed-by: Oswald Buddenhagen <oswald.buddenhagen@theqtcompany.com>
Reviewed-by: Tor Arne Vestbø <tor.arne.vestbo@digia.com>
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>

cregit: 32b7eb8e986b8e30fe68d91c7a30bbc5a95593bd https://github.com/qt/qtbase/commit/32b7eb8e986b8e30fe68d91c7a30bbc5a95593bd