Simplify a function to fix a warning reported by ICC
ICC thinks that the return statement is missing:
src/plugins/accessible/widgets/itemviews.cpp(867): error #1011: missing return statement at end of non-void function "QAccessibleTableHeaderCell::parent"

Clearly it's wrong, but the function is overly complex for no good
reason. So just simplify it instead.

Change-Id: Ic63029df18b4712d9864a4dc66b6751b2d4574b7
Reviewed-by: Jan Arve Sæther <jan-arve.saether@digia.com>
Reviewed-by: Frederik Gladhorn <frederik.gladhorn@digia.com>

cregit: 7abc1a6a828eb36d26901d4ea5ecf8b4514f3cd7 https://github.com/qt/qtbase/commit/7abc1a6a828eb36d26901d4ea5ecf8b4514f3cd7