Remove unused member m_eglApi
It's not used anywhere. Found by Clang 3.4:

qeglplatformcontext_p.h:80:13: error: private field 'm_eglApi' is not used [-Werror,-Wunused-private-field]

Change-Id: I37ce240a9d07ef570e0814de366dbb7cd13ad714
Reviewed-by: Robin Burchell <robin+qt@viroteck.net>

cregit: 52441ecd44d1feb049a152d5e585e89a910a5cd2 https://github.com/qt/qtbase/commit/52441ecd44d1feb049a152d5e585e89a910a5cd2