Fix compilation on libxcb 1.5
libxkbcommon-x11 uses xcb_discard_reply() function which was
introduced in libxcb 1.6, this brakes the compilation in
src/3rdparty/xkbcommon/src/x11/util.c when linking with libxcb 1.5 :

linking ../../../../plugins/platforms/libqxcb.so
.obj/util.o: In function \`adopt_atoms':
util.c:(.text+0x347): undefined reference to \`xcb_discard_reply'
collect2: error: ld returned 1 exit status

We can use an alternative approach to discard uncollected replies
and in addition add a fix for out-of-bounds error [1]

[1] https://github.com/xkbcommon/libxkbcommon/commit/e3f751be660e28e48d1477660e99e5456c864296

Task-number: QTBUG-38952
Change-Id: Ide90f9a2e75fc79d2bab0b81adb282c8cc81c345
Reviewed-by: Jørgen Lind <jorgen.lind@digia.com>

cregit: ba28ca60f66c83a1caa5777d78ffac63e92dfec3 https://github.com/qt/qtbase/commit/ba28ca60f66c83a1caa5777d78ffac63e92dfec3