Consistently hide the parts that require xcb-xkb
It was inconsistent. This also solves a warning from Clang 3.4:
error: private field 'vmod_masks' is not used [-Werror,-Wunused-private-field]

Change-Id: I6be9f7ef56dffe6df2be3beb984c2d82d3808403
Reviewed-by: Gatis Paeglis <gatis.paeglis@digia.com>

cregit: 6c8ecf1000a5defef40348bfda5527dabb57ecf4 https://github.com/qt/qtbase/commit/6c8ecf1000a5defef40348bfda5527dabb57ecf4