Fixed narrowing conversion compile error with SwizzleValue cast.
I got the following compile error with gcc 4.7.0:

  error: narrowing conversion of ‘r’ from ‘QOpenGLTexture::SwizzleValue’ to
  ‘GLint {aka int}’ inside { } [-Werror=narrowing]

The compiler must being going through the route of treating the enum
as an unsigned int and thus choking on the conversion to a signed int.

Change-Id: I35c15673d0371c69984bdec80622066f792527ba
Reviewed-by: Sean Harmer <sean.harmer@kdab.com>
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>

cregit: 2c7ad71adbdb00924b3d7797339dbcf8d6d86479 https://github.com/qt/qtbase/commit/2c7ad71adbdb00924b3d7797339dbcf8d6d86479