Remove calls to setlocale in QtOpenGL cube example.
This is causing compilation errors on some Windows CE
configurations:

mainwidget.cpp(130) : error C3861: 'setlocale': identifier not found
mainwidget.cpp(149) : error C3861: 'setlocale': identifier not found

Change-Id: Ie863cd7c9c53cfef4074dabffe157d9068654a1c
Reviewed-by: Laszlo Agocs <laszlo.agocs@digia.com>
Reviewed-by: Gunnar Sletta <gunnar.sletta@jollamobile.com>

cregit: 23a79b9119fdd05837feff55c1444d53245138bf https://github.com/qt/qtbase/commit/23a79b9119fdd05837feff55c1444d53245138bf